# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='No Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
